#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
echo 'Pre-commit hook running...'


if git diff --cached --name-only | grep -q "package-lock.json"; then
  echo "⚠️  Warning: Removing package-lock.json from commit..."
  git restore --staged package-lock.json  
fi

npx prettier --write .
npx lint-staged
